### ISSUE TITLE
more detail

### ISSUE THREAD

**Issue by chengyalong123** [ThomasWestfechtel/GSDE#1]
Hello, I would like to ask if you can provide label_c.txt in more detail.

**Comment by ThomasWestfechtel** [comment]
I added the label_c.txt files for Office31 in the folder datasets.
The path to the dataset has to be adjusted in the file.

**Comment by Zzzhangxd** [comment]
Reusing the Task-specific Classifier as a Discriminator:Discriminator-free Adversarial Domain Adaptation 请问有复现过这篇论文吗?可以提供完整代码吗
